---
title: "Dimensi Struktural Ruang publik"
author: "Ujang Fahmi"
date: "4/11/2018"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

# Pendahuluan
Halaman ini merupakan catatan penelitian tentang keberadaan ruang publik di balik sebuah tagar yang digunakan di media sosial. Keberadaan ruang publik di sini diidentifikasi melalui tiga dimensi ruang publik, yaitu: (1) dimensi struktural; (2) dimensi representasional; dan (3) dimensi interaksional. Identifikasi terhadap tiga dimensi tersebut dibagi menjadi di folder. Bagian ini akan berusahan mengidentifikasi, menjelaskan, dan memaknai berbagai aktivitas warga net di Twitter terkait dengan keberadaan tagar #jogjaoradidol di twitter. Berikut adalah pertanyaan yang mencoba dijawab: 

  > Bagaimana keterlibatan masyarakat dalam penggunaan tagar #jogjaoradidol di Twitter?

Untuk menjawab pertanyaan tersebut, tiga indikator dimensi struktural ruang publik, yaitu: (1) inklusif ada kesempatan yang sama untuk terlibat dalam diskuis; (2) bebas dari kepentingan kekuasaan dan ekonomi; dan memungkinkan terbentuknya opini publik. 
